version: "3.9"

services:
  db:
    image: postgres:15-alpine
    command: postgres -c 'max_connections=1000'
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8082:80
    depends_on:
      - db
    restart: always

volumes:
  db:
  pgadmin: