version: "3.9"

services:
  app:
    build: .
    volumes:
      - ../../key_finder_client:/app
    restart: "no"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../../key_finder_client:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.key-finder.rule=Host(`key-finder.run-on.app`)
      - traefik.http.routers.key-finder.tls=true
      - traefik.http.routers.key-finder.tls.certresolver=le
    networks:
      - default
      - traefik-proxy
    restart: always

networks:
  traefik-proxy:
    external: true
